## Pre-declare environmental variables
environment-template-common: &environment-template-common
  DEBIAN_FRONTEND: "noninteractive"
  DEBIAN_PRIORITY: "critical"
  DEBCONF_NOWARNINGS: "yes"
  DEBFULLNAME: "GobySoft CircleCI"
  DEBEMAIL: "toby@gobysoft.org"

environment-template-amd64: &environment-template-amd64
  TARGET_ARCH: "amd64"
  DEB_BUILD_OPTIONS: "parallel=4"

environment-template-arm64: &environment-template-arm64
  TARGET_ARCH: "arm64"
  DEB_BUILD_OPTIONS: "parallel=4 nocheck"
  
environment-template-armhf: &environment-template-armhf
  TARGET_ARCH: "armhf"
  DEB_BUILD_OPTIONS: "parallel=4 nocheck"
  
environment-template-xenial: &environment-template-stretch
  DISTRO_RELEASE_CODENAME: "stretch"
  DISTRO_RELEASE_VERSION: "9"

environment-template-xenial: &environment-template-xenial
  DISTRO_RELEASE_CODENAME: "xenial"
  DISTRO_RELEASE_VERSION: "16.04"
  
environment-template-bionic: &environment-template-bionic
  DISTRO_RELEASE_CODENAME: "bionic"
  DISTRO_RELEASE_VERSION: "18.04"

## Pre-declare Docker containers
docker-base-stretch: &docker-base-stretch
  - image: gobysoft/dccl-debian-build-base:9.1
docker-arm64-stretch: &docker-arm64-stretch
  - image: gobysoft/dccl-debian-build-arm64:9.1
docker-armhf-stretch: &docker-armhf-stretch
  - image: gobysoft/dccl-debian-build-armhf:9.1

docker-base-xenial: &docker-base-xenial
  - image: gobysoft/dccl-ubuntu-build-base:16.04.1
docker-arm64-xenial: &docker-arm64-xenial
  - image: gobysoft/dccl-ubuntu-build-arm64:16.04.1
docker-armhf-xenial: &docker-armhf-xenial
  - image: gobysoft/dccl-ubuntu-build-armhf:16.04.1
  
docker-base-bionic: &docker-base-bionic
  - image: gobysoft/dccl-ubuntu-build-base:18.04.1
docker-arm64-bionic: &docker-arm64-bionic
  - image: gobysoft/dccl-ubuntu-build-arm64:18.04.1
docker-armhf-bionic: &docker-armhf-bionic
  - image: gobysoft/dccl-ubuntu-build-armhf:18.04.1

## Pre-declare job templates
job-template-amd64: &job-template-amd64
  working_directory: /root/dccl3
  steps:
    - checkout
    - run: &run-update-apt
        name: Update apt packages
        command: apt-get update && apt-get dist-upgrade -y
    - run: &run-import-gpg
        name: Import GPG key
        command: echo -e "$GPG_KEY" | gpg --import
    - run: &run-update-deb
        name: Update the debian source repo and pull the branch with the same name as the project branch (if it exists)
        command: >-
          cd /root/debian &&
          git pull &&
          git checkout origin/${CIRCLE_BRANCH} ||
          echo "No branch in debian called ${CIRCLE_BRANCH}, using $(git rev-parse --abbrev-ref HEAD)"
    - run: &run-nest-deb
        name: Nest debian source into project source
        command: mv /root/debian ${CIRCLE_WORKING_DIRECTORY}
    - run: &run-dch
        name: Add changelog entry
        command: NEWVERSION="$(git describe --tags HEAD | sed 's/_/~/' | sed 's/-/+/g')" &&  COMMENT="Autobuild for commit $(git log -1 --pretty=oneline)" && cd debian && dch --newversion=${NEWVERSION}-0~${DISTRO_RELEASE_VERSION}.1 -D ${DISTRO_RELEASE_CODENAME} "${COMMENT}"
    - run: &run-build-pkg
        name: Build the Debian package
        command: export CONFIG_SITE=/etc/dpkg-cross/cross-config.${TARGET_ARCH} && dpkg-buildpackage -k19478082E2F8D3FE -b -a${TARGET_ARCH} 
    - run: &run-store-next-build
        name: Store deb files for next build
        command: mkdir -p /root/deb && cp ../*.*deb ../*.changes /root/deb && rm -f /root/deb/*-build-deps*.deb
    - run: &run-store-for-artifacts
        name: Store deb files for storing artifacts
        command: mkdir -p /tmp/deb && cp ../*.deb /tmp/deb
    - persist_to_workspace: &persist-debs
        root: /root/deb
        paths:
          - '*.deb'
    - store_artifacts: &store
        path: /tmp/deb
        
job-template-arm64: &job-template-arm64
  <<: *job-template-amd64
  steps: &steps-cross-compile
    - checkout
    - run: *run-update-apt
    - run: *run-import-gpg
    - attach-workspace: &attach-deb-workspace
        at: /root/deb
    - run: &install-amd64-dccl-compiler
        name: Install amd64 dccl3-compiler so that we can execute it in this cross-build container
        command: dpkg -i /root/deb/dccl3-compiler_*amd64.deb
    - run: *run-update-deb
    - run: *run-nest-deb
    - run: *run-dch
    - run: *run-build-pkg
    - run: *run-store-next-build
    - run: *run-store-for-artifacts
    - persist_to_workspace: *persist-debs
    - store_artifacts: *store

job-template-armhf: &job-template-armhf
  <<: *job-template-amd64
  steps: *steps-cross-compile

# base sanitizer and upload off Bionic build
job-template-sanitizers: &job-template-sanitizers
  <<: *job-template-amd64
  environment:
    <<: *environment-template-common
    <<: *environment-template-bionic
    <<: *environment-template-amd64
    SANITIZER_NUM_JOBS: 2
  docker: *docker-base-bionic

job-template-upload: &job-template-upload
  <<: *job-template-amd64
  environment:
    <<: *environment-template-common
    <<: *environment-template-bionic
    <<: *environment-template-amd64
    SANITIZER_NUM_JOBS: 2
  docker: *docker-base-bionic

  
## Begin actual config
version: 2
workflows:
  version: 2
  commit:
    jobs:
      - amd64-stretch-build
      - arm64-stretch-build:
         requires:
            - amd64-stretch-build
      - armhf-stretch-build:
         requires:
            - arm64-stretch-build

      - amd64-xenial-build
      - arm64-xenial-build:
         requires:
            - amd64-xenial-build
      - armhf-xenial-build:
         requires:
            - arm64-xenial-build
            
      - amd64-bionic-build
      - arm64-bionic-build:
         requires:
            - amd64-bionic-build
      - armhf-bionic-build:
         requires:
            - arm64-bionic-build

      - continuous-upload:
          requires:
            - armhf-stretch-build
            - armhf-bionic-build
            - armhf-xenial-build
            
      - amd64+scan-build:
         requires:
            - amd64-bionic-build
      - amd64+asan-build:
         requires:
            - amd64-bionic-build
      - amd64+tsan-build:
         requires:
            - amd64-bionic-build
      - amd64+ubsan-build:
         requires:
            - amd64-bionic-build
            
jobs:
  amd64-stretch-build:
    <<: *job-template-amd64
    docker: *docker-base-stretch
    environment:
      <<: *environment-template-common
      <<: *environment-template-stretch
      <<: *environment-template-amd64
  arm64-stretch-build: 
    <<: *job-template-arm64
    docker: *docker-arm64-stretch
    environment:
      <<: *environment-template-common
      <<: *environment-template-stretch
      <<: *environment-template-arm64
  armhf-stretch-build: 
    <<: *job-template-armhf
    docker: *docker-armhf-stretch
    environment:
      <<: *environment-template-common
      <<: *environment-template-stretch
      <<: *environment-template-armhf
  amd64-xenial-build:
    <<: *job-template-amd64
    docker: *docker-base-xenial
    environment:
      <<: *environment-template-common
      <<: *environment-template-xenial
      <<: *environment-template-amd64
  arm64-xenial-build: 
    <<: *job-template-arm64
    docker: *docker-arm64-xenial
    environment:
      <<: *environment-template-common
      <<: *environment-template-xenial
      <<: *environment-template-arm64
  armhf-xenial-build: 
    <<: *job-template-armhf
    docker: *docker-armhf-xenial
    environment:
      <<: *environment-template-common
      <<: *environment-template-xenial
      <<: *environment-template-armhf
  amd64-bionic-build:
    <<: *job-template-amd64
    docker: *docker-base-bionic
    environment:
      <<: *environment-template-common
      <<: *environment-template-bionic
      <<: *environment-template-amd64
  arm64-bionic-build: 
    <<: *job-template-arm64
    docker: *docker-arm64-bionic
    environment:
      <<: *environment-template-common
      <<: *environment-template-bionic
      <<: *environment-template-arm64
  armhf-bionic-build: 
    <<: *job-template-armhf
    docker: *docker-armhf-bionic
    environment:
      <<: *environment-template-common
      <<: *environment-template-bionic
      <<: *environment-template-armhf
  amd64+scan-build:
    <<: *job-template-sanitizers
    steps:
      - checkout
      - run: *run-update-apt
      - run:
          name: Build with static analyzer
          command: mkdir -p build && cd build && scan-build cmake .. -Denable_testing=OFF && scan-build --use-c++=/usr/bin/clang++ cmake --build . -- -j${SANITIZER_NUM_JOBS}
      - run:
          name: Store static analyzer results
          command: cd /tmp && tar cfvz scan-build.tar.gz scan-build*
      - store_artifacts: 
          path: /tmp/scan-build.tar.gz
  amd64+asan-build:
    <<: *job-template-sanitizers
    steps:
      - checkout
      - run: *run-update-apt
      - run:
          name: Build with AddressSanitizer (and LeakSanitizer)
          command: mkdir -p build && cd build && cmake -DSANITIZE_ADDRESS=ON -Denable_testing=ON .. && cmake --build . -- -j${SANITIZER_NUM_JOBS}
      - run: &run-tests
          name: Run tests
          command: cd build && ctest --output-on-failure
  amd64+tsan-build:
    <<: *job-template-sanitizers
    steps:
      - checkout
      - run: *run-update-apt
      - run: 
          name: Build with ThreadSanitizer
          command: mkdir -p build && cd build && cmake -DSANITIZE_THREAD=ON -Denable_testing=ON .. && cmake --build . -- -j${SANITIZER_NUM_JOBS}
      - run: *run-tests
  amd64+ubsan-build:
    <<: *job-template-sanitizers
    steps:
      - checkout
      - run: *run-update-apt
      - run:
          name: Build with UndefinedBehaviorSanitizer
          command: mkdir -p build && cd build && cmake -DSANITIZE_UNDEFINED=ON -Denable_testing=ON .. && cmake --build . -- -j${SANITIZER_NUM_JOBS}
      - run: *run-tests
  continuous-upload:
    <<: *job-template-upload
    steps:
      - checkout
      - attach-workspace: *attach-deb-workspace
      - run: &run-install-dput
          name: Install dput
          command: apt-get update && apt-get -y install dput
      - run:
          name: Upload packages to packages.gobysoft.org
          command: for change_file in /root/deb/*.changes; do dput -c ${CIRCLE_WORKING_DIRECTORY}/.circleci/dput.cf gobysoft-continuous $change_file; done      
  release-upload:
    <<: *job-template-upload
    steps:
      - checkout
      - attach-workspace: *attach-deb-workspace
      - run: *run-install-dput
      - run:
          name: Upload packages to packages.gobysoft.org
          command: for change_file in /root/deb/*.changes; do dput -c ${CIRCLE_WORKING_DIRECTORY}/.circleci/dput.cf gobysoft-release $change_file; done      
