version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps: 
      - checkout
      - run: apt-get update && apt-get install -y cmake libboost-dev libcrypto++-dev libprotobuf-dev libprotoc-dev protobuf-compiler libb64-dev doxygen graphviz
      - run: cd dccl/build && cmake --build .
      - run: cd dccl/build && make test
