version: 2
jobs:
  build:
    docker:
      - image: tsaubergine/dccl-circleci:0.0.1
    steps: 
      - checkout
      - run: cd /root/project/build && cmake .. -Denable_testing=ON && make -j4
      - run: cd /root/project/build && make test
