version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps: 
      - checkout
      - run: apt-get update && apt-get install -y cmake libboost-dev libcrypto++-dev libprotobuf-dev libprotoc-dev protobuf-compiler libb64-dev doxygen graphviz build-essential git
      - run: cd /root/project/build && cmake .. -Denable_testing=ON && make -j4
      - run: cd /root/project/build && make test
